apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: default
spec:
  containers:
  - image: bitnami/kubewatch #using this image, its more stable and active
    imagePullPolicy: Always
    name: kubewatch
    env:
    - name: KW_CONFIG
      value: /root
    volumeMounts:
    - name: config-volume
      mountPath: /root
  restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch
