apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
data:
  .kubewatch.yaml: |
    namespace:
      - namespaceOne
      - namespaceTwo
    handler:
      slack:
        token: xxx
        channel: xxx
    resource:
      namespace: false
      deployment: false
      replicationcontroller: false
      replicaset: false
      daemonset: false
      services: false
      pod: true
      secret: false
      configmap: false